[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = ['python3.11 -m venv --copies /opt/venv', '. /opt/venv/bin/activate && pip install -r requirements.txt']

[phases.start]
cmd = 'cd backend && python main.py'
