services:  # Backend API Service
  - type: web
    name: smart-contract-rewriter-backend
    env: python
    plan: starter
    region: oregon
    buildCommand: "pip install -r requirements.txt && alembic upgrade head"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /health
    repo: https://github.com/yourusername/smart_contract_rewriter
    branch: main
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        # **No fromDatabase here** since you use external DB
        # Set this manually in Render dashboard with your existing DB connection string
        sync: false

      - key: GEMINI_API_KEY
        sync: false  # Set manually in Render dashboard

      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: "false"

      - key: LOG_LEVEL
        value: "INFO"

      - key: ALLOWED_ORIGINS
        value: "https://smart-contract-rewriter.onrender.com"

      - key: APP_NAME
        value: "Smart Contract Rewriter"

      - key: APP_VERSION
        value: "1.0.0"

      - key: PYTHONUNBUFFERED
        value: "1"

      # Additional required environment variables
      - key: GEMINI_MODEL
        value: "gemini-1.5-flash"

      - key: WEB3_PROVIDER_URL
        value: "https://mainnet.infura.io/v3/65f7a81362074c3cb170e6311d2438cf"

      - key: ETHEREUM_NETWORK
        value: "mainnet"

      - key: ALGORITHM
        value: "HS256"

      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"

      - key: MAX_FILE_SIZE
        value: "10485760"

      - key: ALLOWED_EXTENSIONS
        value: ".sol,.txt"

      - key: RATE_LIMIT_PER_MINUTE
        value: "30"

      - key: RATE_LIMIT_BURST
        value: "5"

  # Frontend Static Site
  - type: web
    name: smart-contract-rewriter
    env: static
    buildCommand: "cd frontend && npm ci && npm run build"
    staticPublishPath: frontend/dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://smart-contract-rewriter-backend.onrender.com"
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: same-origin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
  # Redis Cache (Optional)
  - type: redis
    name: smart-contract-cache
    plan: starter
    region: oregon
    maxmemoryPolicy: allkeys-lru
    ipAllowList:
      - source: 0.0.0.0/0
        description: "Allow all (modify for production)"

