services:
  # Backend API Service
  - type: web
    name: smart-contract-backend
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        # **No fromDatabase here** since you use external DB
        # Set this manually in Render dashboard with your existing DB connection string
        sync: false

      - key: GEMINI_API_KEY
        sync: false  # Set manually in Render dashboard

      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: "false"

      - key: LOG_LEVEL
        value: "INFO"

      - key: ALLOWED_ORIGINS
        value: "https://smart-contract-frontend.onrender.com"

      - key: APP_NAME
        value: "Smart Contract Rewriter"

      - key: APP_VERSION
        value: "1.0.0"

      - key: PYTHONUNBUFFERED
        value: "1"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT"

  # Frontend Static Site
  - type: web
    name: smart-contract-frontend
    env: static
    buildCommand: "cd frontend && npm ci && npm run build"
    staticPublishPath: frontend/dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://smart-contract-backend.onrender.com"
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: same-origin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Redis Cache (Optional)
  - type: redis
    name: smart-contract-cache
    plan: starter
    region: oregon
    maxmemoryPolicy: allkeys-lru

autoDeploy: true
branch: main
