global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'your-email@gmail.com'
  smtp_auth_username: 'your-email@gmail.com'
  smtp_auth_password: 'your-app-password'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'

receivers:
  - name: 'web.hook'
    webhook_configs:
    - url: 'http://127.0.0.1:5001/'

  - name: 'critical-alerts'
    email_configs:
    - to: 'your-email@gmail.com'
      subject: '[CRITICAL] Smart Contract Rewriter Alert'
      body: |
        Alert: {{ .GroupLabels.alertname }}
        Description: {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
        Time: {{ .CommonAnnotations.time }}
    slack_configs:
    - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
      channel: '#alerts'
      title: '[CRITICAL] Smart Contract Rewriter Alert'
      text: |
        Alert: {{ .GroupLabels.alertname }}
        Description: {{ range .Alerts }}{{ .Annotations.description }}{{ end }}

  - name: 'warning-alerts'
    email_configs:
    - to: 'your-email@gmail.com'
      subject: '[WARNING] Smart Contract Rewriter Alert'
      body: |
        Alert: {{ .GroupLabels.alertname }}
        Description: {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
        Time: {{ .CommonAnnotations.time }}
    slack_configs:
    - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
      channel: '#alerts'
      title: '[WARNING] Smart Contract Rewriter Alert'
      text: |
        Alert: {{ .GroupLabels.alertname }}
        Description: {{ range .Alerts }}{{ .Annotations.description }}{{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
