---
apiVersion: v1
kind: Namespace
metadata:
  name: smart-contract-rewriter
  labels:
    name: smart-contract-rewriter
    environment: production
    app.kubernetes.io/name: smart-contract-rewriter
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kubectl
  annotations:
    description: "Smart Contract Analysis and Rewriting Platform"
    contact: "devops-team@company.com"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: smart-contract-rewriter
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "5"
    services: "10"
    secrets: "20"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: smart-contract-rewriter
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container