apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: smart-contract-rewriter
data:
  DATABASE_URL: "postgresql://postgres:password123@postgres-service:5432/smart_contract_rewriter"
  API_BASE_URL: "http://backend-service:8000"
  FRONTEND_PORT: "3000"
  GEMINI_MODEL: "gemini-2.0-flash-exp"
  WEB3_PROVIDER_URL: "https://mainnet.infura.io/v3/demo"
  ETHEREUM_NETWORK: "mainnet"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  ALLOWED_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000"
  APP_NAME: "SoliVolt"
  APP_VERSION: "1.0.0"
  DEBUG: "true"
  LOG_LEVEL: "INFO"
  MAX_FILE_SIZE: "10485760"
  ALLOWED_EXTENSIONS: ".sol,.txt"
  RATE_LIMIT_PER_MINUTE: "30"
  RATE_LIMIT_BURST: "5"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: smart-contract-rewriter
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  GEMINI_API_KEY: eW91cl9hY3R1YWxfZ2VtaW5pX2FwaV9rZXlfaGVyZQ==  # your_actual_gemini_api_key_here
  SECRET_KEY: ZGV2X3NlY3JldF9rZXlfY2hhbmdlX2luX3Byb2R1Y3Rpb24=  # dev_secret_key_change_in_production
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM=  # password123
