"""Initial migration

Revision ID: 0a3a62f47835
Revises: 
Create Date: 2025-06-07 12:33:04.567718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a3a62f47835'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('contract_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('contract_name', sa.String(length=255), nullable=True),
    sa.Column('original_code', sa.Text(), nullable=False),
    sa.Column('analysis_report', sa.JSON(), nullable=False),
    sa.Column('vulnerabilities_found', sa.JSON(), nullable=True),
    sa.Column('gas_analysis', sa.JSON(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_analyses_contract_name'), 'contract_analyses', ['contract_name'], unique=False)
    op.create_index(op.f('ix_contract_analyses_id'), 'contract_analyses', ['id'], unique=False)
    op.create_table('contract_rewrites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('contract_name', sa.String(length=255), nullable=True),
    sa.Column('original_code', sa.Text(), nullable=False),
    sa.Column('rewritten_code', sa.Text(), nullable=False),
    sa.Column('optimization_goals', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('rewrite_summary', sa.JSON(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['contract_analyses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_rewrites_contract_name'), 'contract_rewrites', ['contract_name'], unique=False)
    op.create_index(op.f('ix_contract_rewrites_id'), 'contract_rewrites', ['id'], unique=False)
    op.create_table('gemini_api_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('called_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('related_analysis_id', sa.Integer(), nullable=True),
    sa.Column('related_rewrite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['related_analysis_id'], ['contract_analyses.id'], ),
    sa.ForeignKeyConstraint(['related_rewrite_id'], ['contract_rewrites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gemini_api_logs_id'), 'gemini_api_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gemini_api_logs_id'), table_name='gemini_api_logs')
    op.drop_table('gemini_api_logs')
    op.drop_index(op.f('ix_contract_rewrites_id'), table_name='contract_rewrites')
    op.drop_index(op.f('ix_contract_rewrites_contract_name'), table_name='contract_rewrites')
    op.drop_table('contract_rewrites')
    op.drop_index(op.f('ix_contract_analyses_id'), table_name='contract_analyses')
    op.drop_index(op.f('ix_contract_analyses_contract_name'), table_name='contract_analyses')
    op.drop_table('contract_analyses')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
