"""Add contract generation table

Revision ID: add_contract_generation
Revises: 0a3a62f47835
Create Date: 2025-06-17 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_contract_generation'
down_revision = '0a3a62f47835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('contract_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('features', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('generated_code', sa.Text(), nullable=False),
    sa.Column('generation_metadata', sa.JSON(), nullable=True),
    sa.Column('compiler_version', sa.String(length=50), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_generations_contract_name'), 'contract_generations', ['contract_name'], unique=False)
    op.create_index(op.f('ix_contract_generations_id'), 'contract_generations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_generations_id'), table_name='contract_generations')
    op.drop_index(op.f('ix_contract_generations_contract_name'), table_name='contract_generations')
    op.drop_table('contract_generations')
    # ### end Alembic commands ###
